server:
  context-path: /client
  port: 8085
  
security:
  basic:
    enabled: true
  user:
    name: a
    password: a
  oauth2:
    client:
      access-token-uri: http://localhost:8082/server/oauth/token
      user-authorization-uri: http://localhost:8082/server/oauth/authorize    
      authorized-grant-types:
        -authorization_code
        -refresh_token
        -password
      client-id: clientapp
      client-secret: clientsecret
      scope:
        - openid
      
    resource:
      user-info-uri: http://localhost:8082/server/user
      
eureka:
  client:
    serviceUrl:
      #defaultZone: ${eureka.server.url}
      defaultZone: http://localhost:8080/eureka
    fetch-registry: true
    register-with-eureka: true
    